import { SignIn } from "@/components/SignIn";
import { SignOut } from "@/components/SignOut";
import { useUser } from "@supabase/auth-helpers-react";
import Head from "next/head";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? (
        <div>
          <p>Signed in as {user.email}</p>
          <SignOut />
        </div>
      ) : (
        <SignIn />
      )}
    </>
  );
}
